<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-android</TargetFramework>
        <RootNamespace>Xamarin.Badges</RootNamespace>
        <LangVersion>latest</LangVersion>
        <Nullable>disable</Nullable>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    </PropertyGroup>
    <PropertyGroup>
        <SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-android'))">21.0</SupportedOSPlatformVersion>
    </PropertyGroup>
    <ItemGroup Condition=" '$(Configuration)'=='Release' ">
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All"/>
    </ItemGroup>
    <ItemGroup>
        <Compile Include="**\*.cs"/>
        <Compile Remove="obj\**"/>
        <Compile Remove="bin\**"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Xamarin.Badges\Xamarin.Badges.csproj" />
    </ItemGroup>
</Project>